<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE ZZSG_orarend [
<!ELEMENT ZZSG_orarend (ora)+>

<!ELEMENT ora (targy, idopont, helyszin, oktato, szak)>
<!ATTLIST ora id ID #REQUIRED>
<!ATTLIST ora tipus (eloadas | gyakorlat) #REQUIRED>

<!ELEMENT targy (#PCDATA)>

<!ELEMENT idopont (nap, tol, ig)>
<!ELEMENT nap (#PCDATA)>
<!ELEMENT tol (#PCDATA)>
<!ELEMENT ig (#PCDATA)>

<!ELEMENT helyszin (#PCDATA)>
<!ELEMENT oktato (#PCDATA)>
<!ELEMENT szak (#PCDATA)>
]>

<ZZSG_orarend>
    <ora id="o1" tipus="eloadas">
        <targy>Elektrotechnika-elektronika</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>8</tol>
            <ig>10</ig>
        </idopont>
        <helyszin>E3</helyszin>
        <oktato>Szabó Norbert István</oktato>
        <szak>Mérnök-informatikus BSc</szak>
    </ora>

    <ora id="o2" tipus="gyakorlat">
        <targy>Web technológiák 1.</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>10</tol>
            <ig>12</ig>
        </idopont>
        <helyszin>E5</helyszin>
        <oktato>Dr. Agárdi Anita</oktato>
        <szak>Mérnök-informatikus BSc</szak>
    </ora>
    
    <ora id="o3" tipus="gyakorlat">
        <targy>Angol műszaki szaknyelv 1.</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>12</tol>
            <ig>14</ig>
        </idopont>
        <helyszin>A1/223</helyszin>
        <oktato>Dobronyi Eszter</oktato>
        <szak>Mérnök-informatikus BSc</szak>
    </ora>

    <ora id="o4" tipus="gyakorlat">
        <targy>Web technológiák 1.</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>14</tol>
            <ig>16</ig>
        </idopont>
        <helyszin>L101</helyszin>
        <oktato>Dr. Agárdi Anita</oktato>
        <szak>Mérnök-informatikus BSc</szak>
    </ora>

    <ora id="o5" tipus="eloadas">
        <targy>Mobil programozási alapok</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>16</tol>
            <ig>18</ig>
        </idopont>
        <helyszin>L101</helyszin>
        <oktato>Dr. Agárdi Anita</oktato>
        <szak>Mérnök-informatikus BSc</szak>
    </ora>

    <ora id="o6" tipus="gyakorlat">
        <targy>Mobil programozási alapok</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>18</tol>
            <ig>20</ig>
        </idopont>
        <helyszin>L101</helyszin>
        <oktato>Dr. Agárdi Anita</oktato>
        <szak>Mérnök-informatikus BSc</szak>
    </ora>

    <ora id="o7" tipus="gyakorlat">
        <targy>Windows rendszergazda</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>8</tol>
            <ig>10</ig>
        </idopont>
        <helyszin>L103</helyszin>
        <oktato>Dr. Wagner György</oktato>
        <szak>Mérnök-informatikus BSc</szak>
    </ora>

    <ora id="o8" tipus="eloadas">
        <targy>Mesterséges intelligencia alapok</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>10</tol>
            <ig>12</ig>
        </idopont>
        <helyszin>E32</helyszin>
        <oktato>Kunné Dr. Tamás Judit</oktato>
        <szak>Mérnök-informatikus BSc</szak>
    </ora>

    <ora id="o9" tipus="gyakorlat">
        <targy>Mesterséges intelligencia alapok</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>12</tol>
            <ig>14</ig>
        </idopont>
        <helyszin>E32</helyszin>
        <oktato>Fazekas Levente</oktato>
        <szak>Mérnök-informatikus BSc</szak>
    </ora>

    <ora id="o10" tipus="gyakorlat">
        <targy>Elektrotechnika-elektronika</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>14</tol>
            <ig>16</ig>
        </idopont>
        <helyszin>A1/317</helyszin>
        <oktato>Szabó Norbert István</oktato>
        <szak>Mérnök-informatikus BSc</szak>
    </ora>

        <ora id="o11" tipus="eloadas"> 
        <targy>Windows rendszergazda</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>16</tol>
            <ig>18</ig>
        </idopont>
        <helyszin>L103</helyszin>
        <oktato>Dr. Wagner György</oktato>
        <szak>Mérnök-informatikus BSc</szak>
    </ora>

    <ora id="o12" tipus="eloadas">
        <targy>Webes adatkezelő környezetek</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>8</tol>
            <ig>10</ig>
        </idopont>
        <helyszin>A1/310</helyszin>
        <oktato>Dr. Kovács László József</oktato>
        <szak>Mérnök-informatikus BSc</szak>
    </ora>

    <ora id="o13" tipus="gyakorlat">
        <targy>Webes adatkezelő környezetek</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>10</tol>
            <ig>12</ig>
        </idopont>
        <helyszin>L103</helyszin>
        <oktato>Dr. Bednarik László</oktato>
        <szak>Mérnök-informatikus BSc</szak>
    </ora>
</ZZSG_orarend>
