=== zagyvazsombor/FXVAUUWebXML/FXVAUU_1008/FXVAUU_kurzusfelvetel.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">


    <xs:simpleType name="tanevTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{4}/[0-9]{4}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="egyetemTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Miskolci Egyetem" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="idTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z0-9\-]+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="igenNemTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="igen" />
            <xs:enumeration value="nem" />
        </xs:restriction>
    </xs:simpleType>


    <xs:element name="FXVAUU_kurzusfelvetel">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="hallgato" />
                <xs:element ref="kurzusok" />
            </xs:sequence>
            <xs:attribute name="tanÃ©v" type="tanevTipus" use="required" />
            <xs:attribute name="egyetem" type="egyetemTipus" use="required" />
        </xs:complexType>
    </xs:element>


    <xs:element name="hallgato">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="hnev" type="xs:string" />
                <xs:element name="szulev" type="xs:gYear" />
                <xs:element name="szak">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="evf" type="xs:integer" use="required" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:element name="kurzusok">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="kurzus" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="kurzusnev" type="xs:string" />
                            <xs:element name="kredit" type="xs:integer" />
                            <xs:element name="hely" type="xs:string" />
                            <xs:element name="idopont" type="xs:string" />
                            <xs:element name="oktato" type="xs:string" />
                            <xs:element name="oraado" type="xs:string" minOccurs="0" />
                        </xs:sequence>
                        <xs:attribute name="id" type="idTipus" use="required" />
                        <xs:attribute name="jovahagyas" type="igenNemTipus" use="optional" />
                        <xs:attribute name="nyelv" type="xs:string" use="optional" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== zagyvazsombor/FXVAUUWebXML/FXVAUU_1008/FXVAUU_kurzusfelvetel.xml
<?xml version="1.0" encoding="UTF-8"?>

<FXVAUU_kurzusfelvetel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="FXVAUU_kurzusfelvetel.xsd" tanév="2025/2026"
    egyetem="Miskolci Egyetem">
    <hallgato>
        <hnev>Zagyva Zsombor Gábor</hnev>
        <szulev>2002</szulev>
        <szak evf="3">Mérnök-informatikus BSc</szak>
    </hallgato>
    <kurzusok>
        <kurzus id="GEVEE050-B2">
            <kurzusnev>Elektrotechnika-elektronika</kurzusnev>
            <kredit>5</kredit>
            <hely>E3</hely>
            <idopont>Hétfő 8-10</idopont>
            <oktato>Szabó Norbert István</oktato>
        </kurzus>

        <kurzus id="GEIAL331-B2" jovahagyas="igen" nyelv="magyar">
            <kurzusnev>Web technológiák 1.</kurzusnev>
            <kredit>5</kredit>
            <hely>E5</hely>
            <idopont>Hétfő 10-12</idopont>
            <oktato>Dr. Agárdi Anita</oktato>
        </kurzus>

        <kurzus id="GEIAK130-B2">
            <kurzusnev>Mesterséges intelligencia alapok</kurzusnev>
            <kredit>5</kredit>
            <hely>E32</hely>
            <idopont>Kedd 10-12</idopont>
            <oktato>Kunné Dr. Tamás Judit,</oktato>
            <oraado>Fazekas Levente Áron</oraado>
        </kurzus>

        <kurzus id="GEIAL30A-B2" jovahagyas="igen" nyelv="magyar">
            <kurzusnev>Windows rendszergazda</kurzusnev>
            <kredit>5</kredit>
            <hely>L103</hely>
            <idopont>Kedd 8-10</idopont>
            <oktato>Dr. Wagner György</oktato>
        </kurzus>

        <kurzus id="GEIAL335-B2">
            <kurzusnev>Mobil programozási alapok</kurzusnev>
            <kredit>5</kredit>
            <hely>L101</hely>
            <idopont>Hétfő 16-18</idopont>
            <oktato>Dr. Agárdi Anita</oktato>
            <oraado>Dr. Agárdi Anita</oraado>
        </kurzus>
    </kurzusok>
</FXVAUU_kurzusfelvetel>
